#
# artemis live broker config
#
{{- if not .Values.configMaps.live.broker }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "company/artemis/getName" $ }}-broker
  labels: {{ include "company/common/labels/metadata" $ | nindent 4 }}
data:
  broker.xml: |-
{{ tpl (.Files.Get "config/broker-live.xml") $ | indent 4  }}
{{- end }}