{{- if not .Values.auth.existingSecret }}
{{- if .Values.auth.requireLogin }}
#
# Artemis console login credentials
#
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "company/common/names/fullname" . }}-client-secret
  labels: {{ include "company/common/labels/metadata" . | nindent 4 }}
type: kubernetes.io/basic-auth
data:
  username: {{ .Values.auth.username | b64enc }}
  password: {{ .Values.auth.password | b64enc }}

{{- end }}
{{- end }}