{{- if not .Values.auth.existingSecret }}
{{- if .Values.auth.requireLogin }}
#
# Artemis console login credentials
#
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "company/common/names/fullname" . }}-server-secret
  labels: {{ include "company/common/labels/metadata" . | nindent 4 }}
type: Opaque
data:
  USERPASS: {{ printf "%s = %s" .Values.auth.username .Values.auth.password | b64enc }}

{{- end }}
{{- end }}