{{- if .Values.auth.requireLogin }}
#
# artemis login config
#
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "company/common/names/fullname" $ }}-login-config
  labels: {{ include "company/common/labels/metadata" $ | nindent 4 }}
data:
  login.config: |-
{{ tpl (.Files.Get "config/login.config") $ | indent 4  }}
{{- end }}
