{{- if .Values.auth.requireLogin }}
#
# artemis roles properties
#
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "company/common/names/fullname" $ }}-roles-properties
  labels: {{ include "company/common/labels/metadata" $ | nindent 4 }}
data:
  roles.properties: |-
{{ tpl (.Files.Get "config/roles.properties") $ | indent 4  }}
{{- end }}
