#
# artemis backup broker config
#
{{ if .Values.ha.enabled }}
{{- if not .Values.configMaps.backup.broker }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "company/common/names/fullname" $ }}-2-broker
  labels: {{ include "company/common/labels/metadata" $ | nindent 4 }}
data:
  broker.xml: |-
{{ tpl (.Files.Get "config/broker-backup.xml") $ | indent 4  }}
{{- end }}
{{ end }}