#
# Artemis backup service
#
{{ if .Values.ha.enabled }}
kind: Service
apiVersion: v1
metadata:
  name: {{ include "company/common/names/fullname" . }}-2
  labels: {{ include "company/common/labels/metadata" . | nindent 4 }}
    ha-instance: backup
spec:
  ports:
    - name: amqp
      port: 61616
      targetPort: 61616
      {{- if .Values.amqpNodePort }}
      nodePort: {{ .Values.amqpNodePort }}
      {{- end }}
    - name: stomp
      port: 61613
      targetPort: 61613
    - name: metrics
      port: 8162
      targetPort: 8162
    - name: admin
      port: 8161
      targetPort: {{ ternary "oauth-proxy" "admin" .Values.oAuthSidecar.enabled }}
      {{- if .Values.adminNodePort }}
      nodePort: {{ .Values.adminNodePort }}
      {{- end }}
  selector: {{- include "company/common/labels/selector" . | nindent 4 }}
    ha-instance: backup
{{ end }}
