{{- $serverSecret := include " company/common/util/digAndMergeYaml" (dict "root" . "key" "serverSecret") | fromYaml -}}
{{- if ($serverSecret).enabled }}
#
# Artemis console login credentials
#
kind: Secret
apiVersion: v1
metadata:
  name: {{ include " company/common/names/fullname" . }}-server
  labels: {{ include " company/common/labels/metadata" . | nindent 4 }}
type: Opaque
data:
  USERPASS: dXNlciA9IHBhc3N3b3Jk

{{- end }}
